### post a new user
POST http://localhost:3000/classroom/create HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "user_id": "212121",
  "classroom_name": "deportes"
}

### get all user classrooms
GET http://localhost:3000/classroom/classroom/464646 HTTP/1.1

### get all classrooms
GET http://localhost:3000/classroom/all HTTP/1.1


### delete Classroom by ID
DELETE http://localhost:3000/classroom/delete/63e5b801e6be5dbb76351787 HTTP/1.1